<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-Q732QR57" failures="41" tests="70" name="Test" time="1.65" errors="0" timestamp="2019-11-03T20:36:26 IST">
  <testcase classname="checkout.TestCalculator" name="sum" time="0.021"/>
  <testcase classname="checkout.TestCalculator" name="sum" time="0.011"/>
  <testcase classname="checkout.TestCalculator" name="sum" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sum" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sum" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sum" time="0.009">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [2.7]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [2.7]
at checkout.TestCalculator.sum(TestCalculator.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase classname="checkout.TestCalculator" name="sum" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [4.699999999999999]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [4.699999999999999]
at checkout.TestCalculator.sum(TestCalculator.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase classname="checkout.TestCalculator" name="sum" time="0.006">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [10.700000000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [10.700000000000001]
at checkout.TestCalculator.sum(TestCalculator.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase classname="checkout.TestCalculator" name="sum" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [9.700000000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [9.700000000000001]
at checkout.TestCalculator.sum(TestCalculator.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase classname="checkout.TestCalculator" name="sum" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-9.9]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-9.9]
at checkout.TestCalculator.sum(TestCalculator.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sum -->
  <testcase classname="checkout.TestCalculator" name="mult" time="0.015"/>
  <testcase classname="checkout.TestCalculator" name="mult" time="0.006"/>
  <testcase classname="checkout.TestCalculator" name="mult" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="mult" time="0.005"/>
  <testcase classname="checkout.TestCalculator" name="mult" time="0.001"/>
  <testcase classname="checkout.TestCalculator" name="mult" time="0.001">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.0]
at checkout.TestCalculator.mult(TestCalculator.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase classname="checkout.TestCalculator" name="mult" time="0.001">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [4.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [4.0]
at checkout.TestCalculator.mult(TestCalculator.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase classname="checkout.TestCalculator" name="mult" time="0.001">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [13.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [13.0]
at checkout.TestCalculator.mult(TestCalculator.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase classname="checkout.TestCalculator" name="mult" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [11.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [11.0]
at checkout.TestCalculator.mult(TestCalculator.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase classname="checkout.TestCalculator" name="mult" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-16.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-16.0]
at checkout.TestCalculator.mult(TestCalculator.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- mult -->
  <testcase classname="checkout.TestCalculator" name="div" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="div" time="0.001"/>
  <testcase classname="checkout.TestCalculator" name="div" time="0.004">
    <failure type="java.lang.AssertionError" message="did not expect to find [0.0] but found [Infinity]">
      <![CDATA[java.lang.AssertionError: did not expect to find [0.0] but found [Infinity]
at checkout.TestCalculator.div(TestCalculator.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase classname="checkout.TestCalculator" name="div" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="div" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="div" time="0.002">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [0.9285714285714287]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [0.9285714285714287]
at checkout.TestCalculator.div(TestCalculator.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase classname="checkout.TestCalculator" name="div" time="0.003">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [2.357142857142857]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [2.357142857142857]
at checkout.TestCalculator.div(TestCalculator.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase classname="checkout.TestCalculator" name="div" time="0.001">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [6.642857142857144]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [6.642857142857144]
at checkout.TestCalculator.div(TestCalculator.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase classname="checkout.TestCalculator" name="div" time="0.001">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [5.92857142857143]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [5.92857142857143]
at checkout.TestCalculator.div(TestCalculator.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase classname="checkout.TestCalculator" name="div" time="0.002">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-8.071428571428573]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-8.071428571428573]
at checkout.TestCalculator.div(TestCalculator.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase classname="checkout.TestCalculator" name="sub" time="0.017"/>
  <testcase classname="checkout.TestCalculator" name="sub" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sub" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sub" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sub" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sub" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-0.09999999999999987]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-0.09999999999999987]
at checkout.TestCalculator.sub(TestCalculator.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase classname="checkout.TestCalculator" name="sub" time="0.008">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.9]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.9]
at checkout.TestCalculator.sub(TestCalculator.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase classname="checkout.TestCalculator" name="sub" time="0.003">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [7.9]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [7.9]
at checkout.TestCalculator.sub(TestCalculator.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase classname="checkout.TestCalculator" name="sub" time="0.001">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [6.9]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [6.9]
at checkout.TestCalculator.sub(TestCalculator.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase classname="checkout.TestCalculator" name="sub" time="0.001">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-12.700000000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-12.700000000000001]
at checkout.TestCalculator.sub(TestCalculator.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.015"/>
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.002">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.140175425099138]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.140175425099138]
at checkout.TestCalculator.sqrt(TestCalculator.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.002">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.816590212458495]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.816590212458495]
at checkout.TestCalculator.sqrt(TestCalculator.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.001">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [3.0495901363953815]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [3.0495901363953815]
at checkout.TestCalculator.sqrt(TestCalculator.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [2.8809720581775866]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [2.8809720581775866]
at checkout.TestCalculator.sqrt(TestCalculator.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase classname="checkout.TestCalculator" name="sqrt" time="0.002">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [3.361547262794322]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [3.361547262794322]
at checkout.TestCalculator.sqrt(TestCalculator.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- sqrt -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0"/>
  <testcase classname="checkout.TestCalculator" name="pow" time="0.001"/>
  <testcase classname="checkout.TestCalculator" name="pow" time="0.005"/>
  <testcase classname="checkout.TestCalculator" name="pow" time="0.002">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [2.8561000000000005]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [2.8561000000000005]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.001">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [391.3539299999999]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [391.3539299999999]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [646990.1834490004]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [646990.1834490004]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [571.7870000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [571.7870000000001]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [127.69000000000001]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [127.69000000000001]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.007">
    <failure type="java.lang.AssertionError" message="did not expect to find [3.8] but found [2.25]">
      <![CDATA[java.lang.AssertionError: did not expect to find [3.8] but found [2.25]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [48.0] but found [5.911689797688559E32]">
      <![CDATA[java.lang.AssertionError: did not expect to find [48.0] but found [5.911689797688559E32]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [18.0] but found [3.503564037074853E8]">
      <![CDATA[java.lang.AssertionError: did not expect to find [18.0] but found [3.503564037074853E8]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [-1.0] but found [625.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-1.0] but found [625.0]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [9.6] but found [789.0480999999999]">
      <![CDATA[java.lang.AssertionError: did not expect to find [9.6] but found [789.0480999999999]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.015">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [1.3]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [1.3]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [3.3]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [3.3]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [9.3]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [9.3]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [8.3]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [8.3]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
  <testcase classname="checkout.TestCalculator" name="pow" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [34.0] but found [-11.3]">
      <![CDATA[java.lang.AssertionError: did not expect to find [34.0] but found [-11.3]
at checkout.TestCalculator.pow(TestCalculator.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- pow -->
</testsuite> <!-- Test -->
